import pygame
import src.constantes as c
from src import button
pygame.init()
screen = pygame.display.set_mode((c.screen_width + c.side_panel, c.screen_height))


titulo = pygame.image.load(c.titulo_img).convert_alpha()
titulo = pygame.transform.scale_by(titulo, 3.5)
tela_derrota = pygame.image.load(c.derrota_img)
tela_derrota_formatada = pygame.transform.scale(tela_derrota, (592,351))
tela_vitoria = pygame.image.load(c.vitoria_img)
tela_vitoria_formatada = pygame.transform.scale(tela_vitoria,(592,351))
tela_hud = pygame.image.load(c.HUD_img)
tela_hud_formatada = pygame.transform.scale(tela_hud,(352,704))
tela_inicial = pygame.image.load(c.tela_inicial_img)
tela_inicial_formatada = pygame.transform.scale(tela_inicial,(1184,702))
forca = pygame.image.load(c.forca_img)
forca = pygame.transform.scale_by(forca, 1.5)
distancia = pygame.image.load(c.distancia_img)
distancia = pygame.transform.scale_by(distancia, 1.5)
cooldown = pygame.image.load(c.cooldown_img)
cooldown = pygame.transform.scale_by(cooldown, 1.5)
exercito = pygame.image.load(c.exercito_img).convert_alpha()
heart = pygame.image.load(c.heart_img).convert_alpha()
heart = pygame.transform.scale_by(heart, 2)
dinheiro = pygame.image.load(c.dinheiro_img).convert_alpha()
dinheiro = pygame.transform.scale_by(dinheiro, 2)
mapa = pygame.image.load(c.mapa_img).convert_alpha()
buy_button = pygame.image.load(c.buy_button_img).convert_alpha()
buy_button = pygame.transform.scale_by(buy_button, 4)
cancel_button = pygame.image.load(c.cancel_button_img).convert_alpha()
cancel_button = pygame.transform.scale_by(cancel_button, 4)
end_button = pygame.image.load(c.end_button_img).convert_alpha()
end_button = pygame.transform.scale_by(end_button, 4)
restart_button = pygame.image.load(c.restart_button_img).convert_alpha()
restart_button = pygame.transform.scale_by(restart_button, 4)
play_button = pygame.image.load(c.play_button_img).convert_alpha()
play_button = pygame.transform.scale_by(play_button, 4)
times_speed_button = pygame.image.load(c.times_speed_button_img).convert_alpha()
times_speed_button = pygame.transform.scale_by(times_speed_button, 4)
pause_button = pygame.image.load(c.pause_button_img).convert_alpha()
pause_button = pygame.transform.scale_by(pause_button, 4)
continue_button = pygame.image.load(c.continue_button_img).convert_alpha()
continue_button = pygame.transform.scale_by(continue_button, 4)
selling_button = pygame.image.load(c.selling_button_img).convert_alpha()
selling_button = pygame.transform.scale_by(selling_button, 4)
dmg_upgrade = pygame.image.load(c.upgrade_damage_img).convert_alpha()
dmg_upgrade = pygame.transform.scale_by(dmg_upgrade, 4)
range_upgrade = pygame.image.load(c.upgrade_range_img).convert_alpha()
range_upgrade = pygame.transform.scale_by(range_upgrade, 4)
speed_upgrade = pygame.image.load(c.upgrade_speed_img).convert_alpha()
speed_upgrade = pygame.transform.scale_by(speed_upgrade, 4)

buy_button_sprite = button.Button(c.screen_width - 190, 10, buy_button,True)
cancel_button_sprite = button.Button(c.screen_width - 195, 130, cancel_button, True)
end_button_sprite = button.Button((c.screen_width//2) + 10, (c.screen_height//2) - 80, end_button, True)
restart_button_sprite = button.Button((c.screen_width//2), c.screen_height//2 + 30, restart_button, True)
play_button_sprite = button.Button((c.screen_width//2), (c.screen_height//2) + 10, play_button, True)
selling_button_sprite = button.Button(c.screen_width - 195, 75, selling_button,True)
dmg_upgrade_sprite = button.Button(c.screen_width - 190, 150, dmg_upgrade, True)
range_upgrade_sprite = button.Button(c.screen_width - 190, 200, range_upgrade, True)
speed_upgrade_sprite = button.Button(c.screen_width - 190, 250, speed_upgrade, True)
times_speed_sprite = button.Button(c.screen_width- 220, c.screen_height-128-20, times_speed_button, False)
pause_sprite = button.Button(c.screen_width - 60, c.screen_height-128-20, pause_button, True)
continue_sprite = button.Button(c.screen_width- 180, c.screen_height-128-80, continue_button, True)